from __future__ import annotations

import json
from typing import Any

import httpx

from seomind.config import settings


class OllamaClient:
    async def status(self) -> dict[str, Any]:
        try:
            async with httpx.AsyncClient(timeout=2.5) as client:
                response = await client.get(f"{settings.ollama_base_url.rstrip('/')}/api/tags")
            if response.is_error:
                return {"available": False, "models": [], "error": f"HTTP {response.status_code}"}
            models = [str(item.get("name", "")) for item in response.json().get("models", [])]
            return {"available": True, "models": [m for m in models if m]}
        except httpx.HTTPError as exc:
            return {"available": False, "models": [], "error": str(exc)}

    async def _selected_model(self, model: str | None = None) -> str:
        state = await self.status()
        models = state.get("models", []) if state.get("available") else []
        if not models:
            raise RuntimeError("Ollama is running but no local model is installed.")
        configured = settings.ollama_model
        return model or (configured if configured in models else models[0])

    async def _json_chat(self, prompt: str, model: str | None = None) -> dict[str, Any]:
        selected = await self._selected_model(model)
        payload = {
            "model": selected,
            "stream": False,
            "format": "json",
            "messages": [{"role": "user", "content": prompt}],
        }
        async with httpx.AsyncClient(timeout=180) as client:
            response = await client.post(
                f"{settings.ollama_base_url.rstrip('/')}/api/chat",
                json=payload,
            )
        if response.is_error:
            raise RuntimeError(f"Ollama request failed: {response.text[:500]}")
        content = response.json().get("message", {}).get("content", "{}")
        try:
            parsed = json.loads(content)
        except json.JSONDecodeError:
            parsed = {"summary": content.strip()}
        parsed["model"] = selected
        return parsed

    async def explain(self, opportunity: dict[str, Any], language: str, model: str | None) -> dict[str, Any]:
        language_name = "Persian (Farsi)" if language == "fa" else "English"
        prompt = f"""
You are SeoMind, a careful SEO analyst. Explain one deterministic Google Search Console finding.
Do not invent traffic, rankings, causes, or facts that are not in the input.
Write in {language_name}.
Return strict JSON only with these keys:
summary: string (max 2 sentences)
why_it_matters: string (max 2 sentences)
actions: array of exactly 3 short actionable strings

Finding:
{json.dumps(opportunity, ensure_ascii=False)}
""".strip()
        parsed = await self._json_chat(prompt, model)
        parsed.setdefault("why_it_matters", "")
        parsed.setdefault("actions", [])
        return parsed

    async def daily_brief(self, facts: dict[str, Any], language: str = "en", model: str | None = None) -> dict[str, Any]:
        language_name = "Persian (Farsi)" if language == "fa" else "English"
        prompt = f"""
You are SeoMind Local Assistant, a daily SEO copilot running privately on the user's computer.
You receive structured, factual data generated by Search Console and SeoMind's deterministic crawler.
Never invent rankings, traffic causes, crawl errors, competitors, keywords, or fixes that are not supported by the input.
Distinguish facts from hypotheses. Growth ideas may be hypotheses, but must be tied to a concrete signal from the input.
Write in {language_name}.

Return strict JSON only with:
headline: string
summary: string (2-4 sentences)
alerts: array of up to 5 objects with keys: title, evidence, priority (high|medium|low)
growth_ideas: array of up to 5 objects with keys: title, evidence, action, confidence (high|medium|low)
focus_today: array of exactly 3 concise action strings

Input facts:
{json.dumps(facts, ensure_ascii=False)}
""".strip()
        parsed = await self._json_chat(prompt, model)
        parsed.setdefault("headline", "")
        parsed.setdefault("summary", "")
        parsed.setdefault("alerts", [])
        parsed.setdefault("growth_ideas", [])
        parsed.setdefault("focus_today", [])
        return parsed

    async def assistant_chat(
        self,
        *,
        context: dict[str, Any],
        question: str,
        language: str = "en",
        model: str | None = None,
    ) -> dict[str, Any]:
        language_name = "Persian (Farsi)" if language == "fa" else "English"
        prompt = f"""
You are SeoMind Local Assistant, a private SEO copilot.
Answer the user's question only from the supplied local SEO context.
Never invent rankings, traffic, Search Console metrics, crawl errors, competitors, or completed actions.
When a cause is uncertain, say it is a hypothesis.
Prefer concrete page/query evidence and actionable next steps.
Write in {language_name}.

Return strict JSON with:
answer: string
evidence: array of up to 5 short strings
actions: array of up to 5 short strings
confidence: high|medium|low

Local context:
{json.dumps(context, ensure_ascii=False)}

User question:
{question}
""".strip()
        parsed = await self._json_chat(prompt, model)
        parsed.setdefault("answer", parsed.get("summary", ""))
        parsed.setdefault("evidence", [])
        parsed.setdefault("actions", [])
        parsed.setdefault("confidence", "medium")
        return parsed


ollama = OllamaClient()
