"use client";

import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  Bot,
  BrainCircuit,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  CircleAlert,
  Clock3,
  Lightbulb,
  Loader2,
  MessageCircle,
  RefreshCw,
  Rocket,
  Send,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
} from "lucide-react";
import { api, type AssistantReport, type AssistantStatus } from "@/lib/api";
import type { Lang } from "@/lib/i18n";

const copy = {
  en: {
    title: "SeoMind Local Assistant",
    subtitle: "A private SEO copilot that reviews Search Console, technical health and growth signals every day.",
    run: "Check now",
    running: "Checking site…",
    auto: "Daily automatic check",
    local: "Local AI",
    sourceAI: "Brief generated by Ollama",
    sourceRules: "Evidence-first brief; Ollama not required",
    noReport: "No daily brief yet. Run the first check to create the site's baseline.",
    alerts: "What needs attention",
    growth: "Growth ideas",
    focus: "Today's focus",
    sites: "Monitored sites",
    lastCheck: "Last check",
    askTitle: "Ask SeoMind",
    askPlaceholder: "Why did clicks drop? What should I improve today?",
    askButton: "Ask local AI",
    evidence: "Evidence",
    actions: "Suggested actions",
    scores: { growing: "Growing", stable: "Stable", attention: "Needs attention", critical: "Critical", error: "Check failed" },
  },
  fa: {
    title: "دستیار محلی SeoMind",
    subtitle: "یک دستیار خصوصی سئو که هر روز Search Console، سلامت فنی و فرصت‌های رشد سایت را بررسی می‌کند.",
    run: "بررسی همین الان",
    running: "در حال بررسی سایت…",
    auto: "بررسی خودکار روزانه",
    local: "هوش مصنوعی محلی",
    sourceAI: "گزارش توسط Ollama روی سیستم شما ساخته شده",
    sourceRules: "گزارش مبتنی بر داده؛ بدون Ollama هم کار می‌کند",
    noReport: "هنوز گزارش روزانه‌ای ساخته نشده است. اولین بررسی را اجرا کنید تا خط پایه سایت ایجاد شود.",
    alerts: "موارد نیازمند توجه",
    growth: "ایده‌های رشد",
    focus: "تمرکز امروز",
    sites: "سایت‌های تحت‌نظر",
    lastCheck: "آخرین بررسی",
    askTitle: "از SeoMind بپرس",
    askPlaceholder: "چرا کلیک افت کرده؟ امروز روی کدام صفحه کار کنم؟",
    askButton: "پرسش از AI محلی",
    evidence: "شواهد",
    actions: "اقدام‌های پیشنهادی",
    scores: { growing: "در حال رشد", stable: "پایدار", attention: "نیازمند توجه", critical: "بحرانی", error: "خطای بررسی" },
  },
} as const;

function statusClass(status: string) {
  if (status === "growing") return "border-emerald-400/20 bg-emerald-400/10 text-emerald-200";
  if (status === "stable") return "border-sky-400/20 bg-sky-400/10 text-sky-200";
  if (status === "attention") return "border-amber-400/20 bg-amber-400/10 text-amber-200";
  return "border-rose-400/20 bg-rose-400/10 text-rose-200";
}

function priorityClass(priority: string) {
  if (priority === "high") return "text-rose-300";
  if (priority === "medium") return "text-amber-300";
  return "text-sky-300";
}

export default function AssistantPanel({ lang, selectedSite, aiAvailable }: { lang: Lang; selectedSite: string | null; aiAvailable: boolean }) {
  const t = copy[lang];
  const [state, setState] = useState<AssistantStatus | null>(null);
  const [running, setRunning] = useState(false);
  const [open, setOpen] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [question, setQuestion] = useState("");
  const [asking, setAsking] = useState(false);
  const [answer, setAnswer] = useState<{ answer: string; evidence: string[]; actions: string[]; confidence: string; model?: string } | null>(null);

  async function load() {
    try { setState(await api.assistantStatus()); setError(null); }
    catch (e) { setError(e instanceof Error ? e.message : String(e)); }
  }

  useEffect(() => { load(); }, []);

  async function runNow() {
    setRunning(true); setError(null);
    try {
      await api.assistantRun(lang, selectedSite || undefined);
      await load();
    } catch (e) { setError(e instanceof Error ? e.message : String(e)); }
    finally { setRunning(false); }
  }

  async function askSeoMind() {
    if (!question.trim() || !aiAvailable) return;
    setAsking(true); setError(null);
    try {
      setAnswer(await api.assistantAsk(question.trim(), lang, selectedSite || undefined));
    } catch (e) { setError(e instanceof Error ? e.message : String(e)); }
    finally { setAsking(false); }
  }

  const report = useMemo(() => {
    if (!state?.reports.length) return null;
    return state.reports.find((item) => item.site_url === selectedSite) || state.reports[0];
  }, [state, selectedSite]);

  return (
    <section className="mb-7 overflow-hidden rounded-[28px] border border-violet-400/15 bg-gradient-to-br from-violet-500/[0.10] via-slate-950/75 to-sky-500/[0.07] shadow-glow">
      <div className="p-6 md:p-7">
        <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
          <div className="flex items-start gap-4">
            <div className="relative flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-violet-300/20 bg-violet-400/10">
              <BrainCircuit className="h-7 w-7 text-violet-200" />
              <span className="absolute -bottom-1 -right-1 flex h-5 w-5 items-center justify-center rounded-lg border border-slate-800 bg-slate-950"><Sparkles className="h-3 w-3 text-sky-300" /></span>
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <h2 className="text-2xl font-black">{t.title}</h2>
                <span className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[11px] font-bold text-slate-300">
                  <Bot className="h-3.5 w-3.5" />{t.local}
                </span>
              </div>
              <p className="mt-2 max-w-3xl text-sm leading-7 text-slate-400">{t.subtitle}</p>
              <div className="mt-3 flex flex-wrap items-center gap-3 text-[11px] text-slate-500">
                <span className="inline-flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" />{t.auto}: {String(state?.daily_hour ?? 9).padStart(2, "0")}:00</span>
                <span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5" />{aiAvailable ? t.sourceAI : t.sourceRules}</span>
              </div>
            </div>
          </div>
          <button onClick={runNow} disabled={running || !selectedSite} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-300 to-sky-300 px-5 py-3 text-sm font-black text-slate-950 transition hover:brightness-110 disabled:opacity-50">
            {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
            {running ? t.running : t.run}
          </button>
        </div>

        {error && <div className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</div>}

        {!report ? (
          <div className="mt-6 rounded-2xl border border-dashed border-white/10 bg-slate-950/20 p-8 text-center text-sm text-slate-500">{t.noReport}</div>
        ) : (
          <div className="mt-6">
            <div className="grid gap-3 md:grid-cols-[150px_1fr]">
              <div className={`rounded-2xl border p-5 ${statusClass(report.status)}`}>
                <div className="text-xs font-bold opacity-70">{t.scores[report.status as keyof typeof t.scores] || report.status}</div>
                <div className="mt-2 text-4xl font-black">{report.health_score}<span className="text-sm opacity-60">/100</span></div>
                <div className="mt-3 text-[10px] opacity-60">{report.report_date}</div>
              </div>
              <div className="rounded-2xl border border-white/[0.07] bg-slate-950/25 p-5">
                <div className="flex items-start justify-between gap-3">
                  <div><div className="text-xl font-black text-white">{report.brief.headline}</div><p className="mt-2 text-sm leading-7 text-slate-400">{report.brief.summary}</p></div>
                  <button onClick={() => setOpen(!open)} className="rounded-xl border border-white/10 bg-white/[0.03] p-2 text-slate-400">{open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</button>
                </div>
                <div className="mt-3 truncate text-[11px] text-slate-600">{report.site_url}</div>
              </div>
            </div>

            {open && (
              <div className="mt-4 grid gap-4 xl:grid-cols-3">
                <BriefColumn icon={CircleAlert} title={t.alerts}>
                  {report.brief.alerts?.length ? report.brief.alerts.map((item, index) => (
                    <div key={index} className="rounded-xl border border-white/[0.06] bg-slate-950/30 p-3">
                      <div className={`text-xs font-black ${priorityClass(item.priority)}`}>{item.title}</div>
                      <div className="mt-1 text-xs leading-5 text-slate-500">{item.evidence}</div>
                    </div>
                  )) : <Empty good />}
                </BriefColumn>

                <BriefColumn icon={Lightbulb} title={t.growth}>
                  {report.brief.growth_ideas?.length ? report.brief.growth_ideas.map((item, index) => (
                    <div key={index} className="rounded-xl border border-white/[0.06] bg-slate-950/30 p-3">
                      <div className="flex items-start gap-2"><TrendingUp className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" /><div className="text-xs font-black text-slate-200">{item.title}</div></div>
                      <div className="mt-2 text-[11px] leading-5 text-slate-500">{item.evidence}</div>
                      <div className="mt-2 text-xs leading-5 text-sky-200/80">{item.action}</div>
                    </div>
                  )) : <Empty good />}
                </BriefColumn>

                <BriefColumn icon={Target} title={t.focus}>
                  {(report.brief.focus_today || []).map((item, index) => (
                    <div key={index} className="flex items-start gap-3 rounded-xl border border-white/[0.06] bg-slate-950/30 p-3">
                      <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-violet-400/10 text-[11px] font-black text-violet-200">{index + 1}</span>
                      <div className="text-xs leading-6 text-slate-300">{item}</div>
                    </div>
                  ))}
                </BriefColumn>
              </div>
            )}
          </div>
        )}

        <div className="mt-6 rounded-2xl border border-sky-400/15 bg-sky-400/[0.045] p-4 md:p-5">
          <div className="flex items-center gap-2 text-sm font-black text-sky-100"><MessageCircle className="h-4 w-4 text-sky-300" />{t.askTitle}</div>
          <div className="mt-3 flex flex-col gap-2 sm:flex-row">
            <input
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && askSeoMind()}
              disabled={!aiAvailable}
              placeholder={t.askPlaceholder}
              className="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-950/45 px-4 py-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-sky-400/35 disabled:opacity-50"
            />
            <button onClick={askSeoMind} disabled={!aiAvailable || asking || !question.trim()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-sky-300 px-4 py-3 text-xs font-black text-slate-950 transition hover:bg-sky-200 disabled:opacity-40">
              {asking ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{t.askButton}
            </button>
          </div>
          {!aiAvailable && <div className="mt-2 text-[11px] text-slate-600">Ollama is required for Ask SeoMind.</div>}
          {answer && (
            <div className="mt-4 rounded-xl border border-white/[0.07] bg-slate-950/35 p-4">
              <p className="text-sm leading-7 text-slate-200">{answer.answer}</p>
              {!!answer.evidence?.length && <div className="mt-4"><div className="text-[10px] font-black uppercase tracking-[.14em] text-slate-600">{t.evidence}</div><ul className="mt-2 space-y-1.5 text-xs leading-6 text-slate-400">{answer.evidence.map((item, i) => <li key={i}>• {item}</li>)}</ul></div>}
              {!!answer.actions?.length && <div className="mt-4"><div className="text-[10px] font-black uppercase tracking-[.14em] text-slate-600">{t.actions}</div><ol className="mt-2 space-y-2 text-xs leading-6 text-sky-100/80">{answer.actions.map((item, i) => <li key={i}><span className="mr-2 text-violet-300">{i + 1}.</span>{item}</li>)}</ol></div>}
              <div className="mt-3 text-[10px] text-slate-600">{answer.model || "Ollama"} · confidence: {answer.confidence}</div>
            </div>
          )}
        </div>

        {!!state?.sites.length && (
          <div className="mt-5 border-t border-white/[0.06] pt-4">
            <div className="mb-2 text-[10px] font-bold uppercase tracking-[.16em] text-slate-600">{t.sites}</div>
            <div className="flex flex-wrap gap-2">
              {state.sites.map((site) => {
                const siteReport = state.reports.find((r) => r.site_url === site.site_url);
                return <span key={site.site_url} className="inline-flex max-w-full items-center gap-2 rounded-lg border border-white/[0.06] bg-white/[0.025] px-3 py-2 text-[11px] text-slate-400">
                  {siteReport?.status === "growing" ? <Rocket className="h-3.5 w-3.5 text-emerald-300" /> : <CheckCircle2 className="h-3.5 w-3.5 text-slate-500" />}
                  <span className="max-w-[260px] truncate">{site.label || site.site_url}</span>
                  {siteReport && <strong className={statusClass(siteReport.status).split(" ").pop()}>{siteReport.health_score}</strong>}
                </span>;
              })}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}

function BriefColumn({ icon: Icon, title, children }: { icon: typeof AlertTriangle; title: string; children: React.ReactNode }) {
  return <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4"><div className="mb-3 flex items-center gap-2 text-xs font-black uppercase tracking-[.12em] text-slate-500"><Icon className="h-4 w-4 text-violet-300" />{title}</div><div className="space-y-2">{children}</div></div>;
}

function Empty({ good }: { good?: boolean }) {
  return <div className="flex items-center gap-2 rounded-xl border border-white/[0.05] p-3 text-xs text-slate-600">{good && <CheckCircle2 className="h-4 w-4 text-emerald-400/60" />}—</div>;
}
